version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: db_exercice_php
        target: /var/lib/mysql
    ports:
      - "3001:3306"

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_interface_exercice_php
      restart: always
      depends_on:
          - db
      ports:
          - "8080:80"
      environment:
          PMA_HOST: db

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  db_exercice_php:
    external: true
